language: ruby
rvm:
- 2.2
sudo: false
script: bundle exec asciidoctor -d book -D out -B . -R . -a sectanchors -a docinfo1 index.asciidoc
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: out/
  on:
    branch: master